name: run npm test with reusable workflow
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Aymeric987/sfeir-school-github-actions-aymeric/.github/workflows/ex4.yaml@main
    with:
      node-version: "lts/*"