name: build docker
on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name : setup node
          uses: actions/setup-node@v4
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install
            npm test
  build-docker:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: init docker buildx
          uses: docker/setup-buildx-action@v3

        - name: build docker
          shell: bash
          run: |
            docker build -t ${{ github.sha }} .
    